// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: transport/grpc/proto/umai.proto

package grpcPb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MenuAuthServiceClient is the client API for MenuAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MenuAuthServiceClient interface {
	GetIdentity(ctx context.Context, in *IdentityReq, opts ...grpc.CallOption) (*IdentityRes, error)
}

type menuAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMenuAuthServiceClient(cc grpc.ClientConnInterface) MenuAuthServiceClient {
	return &menuAuthServiceClient{cc}
}

func (c *menuAuthServiceClient) GetIdentity(ctx context.Context, in *IdentityReq, opts ...grpc.CallOption) (*IdentityRes, error) {
	out := new(IdentityRes)
	err := c.cc.Invoke(ctx, "/grpc.MenuAuthService/GetIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MenuAuthServiceServer is the server API for MenuAuthService service.
// All implementations must embed UnimplementedMenuAuthServiceServer
// for forward compatibility
type MenuAuthServiceServer interface {
	GetIdentity(context.Context, *IdentityReq) (*IdentityRes, error)
	mustEmbedUnimplementedMenuAuthServiceServer()
}

// UnimplementedMenuAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMenuAuthServiceServer struct {
}

func (UnimplementedMenuAuthServiceServer) GetIdentity(context.Context, *IdentityReq) (*IdentityRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentity not implemented")
}
func (UnimplementedMenuAuthServiceServer) mustEmbedUnimplementedMenuAuthServiceServer() {}

// UnsafeMenuAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MenuAuthServiceServer will
// result in compilation errors.
type UnsafeMenuAuthServiceServer interface {
	mustEmbedUnimplementedMenuAuthServiceServer()
}

func RegisterMenuAuthServiceServer(s grpc.ServiceRegistrar, srv MenuAuthServiceServer) {
	s.RegisterService(&MenuAuthService_ServiceDesc, srv)
}

func _MenuAuthService_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuAuthServiceServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MenuAuthService/GetIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuAuthServiceServer).GetIdentity(ctx, req.(*IdentityReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MenuAuthService_ServiceDesc is the grpc.ServiceDesc for MenuAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MenuAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.MenuAuthService",
	HandlerType: (*MenuAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIdentity",
			Handler:    _MenuAuthService_GetIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transport/grpc/proto/umai.proto",
}

// MenuItemServiceClient is the client API for MenuItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MenuItemServiceClient interface {
	GetMenuItem(ctx context.Context, in *GetMenuItemReq, opts ...grpc.CallOption) (*GetMenuItemRes, error)
}

type menuItemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMenuItemServiceClient(cc grpc.ClientConnInterface) MenuItemServiceClient {
	return &menuItemServiceClient{cc}
}

func (c *menuItemServiceClient) GetMenuItem(ctx context.Context, in *GetMenuItemReq, opts ...grpc.CallOption) (*GetMenuItemRes, error) {
	out := new(GetMenuItemRes)
	err := c.cc.Invoke(ctx, "/grpc.MenuItemService/GetMenuItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MenuItemServiceServer is the server API for MenuItemService service.
// All implementations must embed UnimplementedMenuItemServiceServer
// for forward compatibility
type MenuItemServiceServer interface {
	GetMenuItem(context.Context, *GetMenuItemReq) (*GetMenuItemRes, error)
	mustEmbedUnimplementedMenuItemServiceServer()
}

// UnimplementedMenuItemServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMenuItemServiceServer struct {
}

func (UnimplementedMenuItemServiceServer) GetMenuItem(context.Context, *GetMenuItemReq) (*GetMenuItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMenuItem not implemented")
}
func (UnimplementedMenuItemServiceServer) mustEmbedUnimplementedMenuItemServiceServer() {}

// UnsafeMenuItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MenuItemServiceServer will
// result in compilation errors.
type UnsafeMenuItemServiceServer interface {
	mustEmbedUnimplementedMenuItemServiceServer()
}

func RegisterMenuItemServiceServer(s grpc.ServiceRegistrar, srv MenuItemServiceServer) {
	s.RegisterService(&MenuItemService_ServiceDesc, srv)
}

func _MenuItemService_GetMenuItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenuItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuItemServiceServer).GetMenuItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.MenuItemService/GetMenuItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuItemServiceServer).GetMenuItem(ctx, req.(*GetMenuItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MenuItemService_ServiceDesc is the grpc.ServiceDesc for MenuItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MenuItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.MenuItemService",
	HandlerType: (*MenuItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMenuItem",
			Handler:    _MenuItemService_GetMenuItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transport/grpc/proto/umai.proto",
}
