// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: transport/grpc/proto/umai.proto

// import "google/protobuf/timestamp.proto";

package grpcPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityResReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *IdentityResReq) Reset() {
	*x = IdentityResReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_proto_umai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityResReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResReq) ProtoMessage() {}

func (x *IdentityResReq) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_proto_umai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResReq.ProtoReflect.Descriptor instead.
func (*IdentityResReq) Descriptor() ([]byte, []int) {
	return file_transport_grpc_proto_umai_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityResReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type IdentityResResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       int32  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Role         string `protobuf:"bytes,2,opt,name=Role,proto3" json:"Role,omitempty"`
	RestaurantID int32  `protobuf:"varint,3,opt,name=RestaurantID,proto3" json:"RestaurantID,omitempty"`
}

func (x *IdentityResResp) Reset() {
	*x = IdentityResResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_proto_umai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityResResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResResp) ProtoMessage() {}

func (x *IdentityResResp) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_proto_umai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResResp.ProtoReflect.Descriptor instead.
func (*IdentityResResp) Descriptor() ([]byte, []int) {
	return file_transport_grpc_proto_umai_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityResResp) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *IdentityResResp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *IdentityResResp) GetRestaurantID() int32 {
	if x != nil {
		return x.RestaurantID
	}
	return 0
}

type IdentityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *IdentityReq) Reset() {
	*x = IdentityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_proto_umai_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityReq) ProtoMessage() {}

func (x *IdentityReq) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_proto_umai_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityReq.ProtoReflect.Descriptor instead.
func (*IdentityReq) Descriptor() ([]byte, []int) {
	return file_transport_grpc_proto_umai_proto_rawDescGZIP(), []int{2}
}

func (x *IdentityReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type IdentityResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *IdentityResp) Reset() {
	*x = IdentityResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_proto_umai_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResp) ProtoMessage() {}

func (x *IdentityResp) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_proto_umai_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResp.ProtoReflect.Descriptor instead.
func (*IdentityResp) Descriptor() ([]byte, []int) {
	return file_transport_grpc_proto_umai_proto_rawDescGZIP(), []int{3}
}

func (x *IdentityResp) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type GetMenuItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMenuItemReq) Reset() {
	*x = GetMenuItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_proto_umai_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemReq) ProtoMessage() {}

func (x *GetMenuItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_proto_umai_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemReq.ProtoReflect.Descriptor instead.
func (*GetMenuItemReq) Descriptor() ([]byte, []int) {
	return file_transport_grpc_proto_umai_proto_rawDescGZIP(), []int{4}
}

func (x *GetMenuItemReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMenuItemRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetMenuItemRes) Reset() {
	*x = GetMenuItemRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_proto_umai_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuItemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemRes) ProtoMessage() {}

func (x *GetMenuItemRes) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_proto_umai_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemRes.ProtoReflect.Descriptor instead.
func (*GetMenuItemRes) Descriptor() ([]byte, []int) {
	return file_transport_grpc_proto_umai_proto_rawDescGZIP(), []int{5}
}

func (x *GetMenuItemRes) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_transport_grpc_proto_umai_proto protoreflect.FileDescriptor

var file_transport_grpc_proto_umai_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x6d, 0x61, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x28, 0x0a, 0x0e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x22, 0x61, 0x0a, 0x0f, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x52, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x49, 0x44, 0x22, 0x25, 0x0a, 0x0b, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x26, 0x0a, 0x0c, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x8e, 0x01, 0x0a, 0x0f,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x3a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x32, 0x4e, 0x0a, 0x0f,
	0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transport_grpc_proto_umai_proto_rawDescOnce sync.Once
	file_transport_grpc_proto_umai_proto_rawDescData = file_transport_grpc_proto_umai_proto_rawDesc
)

func file_transport_grpc_proto_umai_proto_rawDescGZIP() []byte {
	file_transport_grpc_proto_umai_proto_rawDescOnce.Do(func() {
		file_transport_grpc_proto_umai_proto_rawDescData = protoimpl.X.CompressGZIP(file_transport_grpc_proto_umai_proto_rawDescData)
	})
	return file_transport_grpc_proto_umai_proto_rawDescData
}

var file_transport_grpc_proto_umai_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_transport_grpc_proto_umai_proto_goTypes = []interface{}{
	(*IdentityResReq)(nil),  // 0: grpc.IdentityResReq
	(*IdentityResResp)(nil), // 1: grpc.IdentityResResp
	(*IdentityReq)(nil),     // 2: grpc.IdentityReq
	(*IdentityResp)(nil),    // 3: grpc.IdentityResp
	(*GetMenuItemReq)(nil),  // 4: grpc.GetMenuItemReq
	(*GetMenuItemRes)(nil),  // 5: grpc.GetMenuItemRes
}
var file_transport_grpc_proto_umai_proto_depIdxs = []int32{
	0, // 0: grpc.IdentityService.GetResIdentity:input_type -> grpc.IdentityResReq
	2, // 1: grpc.IdentityService.GetUserIdentity:input_type -> grpc.IdentityReq
	4, // 2: grpc.MenuItemService.GetMenuItem:input_type -> grpc.GetMenuItemReq
	1, // 3: grpc.IdentityService.GetResIdentity:output_type -> grpc.IdentityResResp
	3, // 4: grpc.IdentityService.GetUserIdentity:output_type -> grpc.IdentityResp
	5, // 5: grpc.MenuItemService.GetMenuItem:output_type -> grpc.GetMenuItemRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_grpc_proto_umai_proto_init() }
func file_transport_grpc_proto_umai_proto_init() {
	if File_transport_grpc_proto_umai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transport_grpc_proto_umai_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityResReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_proto_umai_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityResResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_proto_umai_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_proto_umai_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_proto_umai_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_proto_umai_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuItemRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transport_grpc_proto_umai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_transport_grpc_proto_umai_proto_goTypes,
		DependencyIndexes: file_transport_grpc_proto_umai_proto_depIdxs,
		MessageInfos:      file_transport_grpc_proto_umai_proto_msgTypes,
	}.Build()
	File_transport_grpc_proto_umai_proto = out.File
	file_transport_grpc_proto_umai_proto_rawDesc = nil
	file_transport_grpc_proto_umai_proto_goTypes = nil
	file_transport_grpc_proto_umai_proto_depIdxs = nil
}
