// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: transport/grpc/proto/umai.proto

package grpcPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int32 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *IdentityReq) Reset() {
	*x = IdentityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_proto_umai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityReq) ProtoMessage() {}

func (x *IdentityReq) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_proto_umai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityReq.ProtoReflect.Descriptor instead.
func (*IdentityReq) Descriptor() ([]byte, []int) {
	return file_transport_grpc_proto_umai_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type IdentityRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       int32  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Role         string `protobuf:"bytes,2,opt,name=Role,proto3" json:"Role,omitempty"`
	RestaurantID int32  `protobuf:"varint,3,opt,name=RestaurantID,proto3" json:"RestaurantID,omitempty"`
}

func (x *IdentityRes) Reset() {
	*x = IdentityRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transport_grpc_proto_umai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRes) ProtoMessage() {}

func (x *IdentityRes) ProtoReflect() protoreflect.Message {
	mi := &file_transport_grpc_proto_umai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRes.ProtoReflect.Descriptor instead.
func (*IdentityRes) Descriptor() ([]byte, []int) {
	return file_transport_grpc_proto_umai_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityRes) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *IdentityRes) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *IdentityRes) GetRestaurantID() int32 {
	if x != nil {
		return x.RestaurantID
	}
	return 0
}

var File_transport_grpc_proto_umai_proto protoreflect.FileDescriptor

var file_transport_grpc_proto_umai_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x6d, 0x61, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x25, 0x0a, 0x0b, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x5d,
	0x0a, 0x0b, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x73,
	0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x32, 0x48, 0x0a,
	0x0f, 0x4d, 0x65, 0x6e, 0x75, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x35, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x1a, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transport_grpc_proto_umai_proto_rawDescOnce sync.Once
	file_transport_grpc_proto_umai_proto_rawDescData = file_transport_grpc_proto_umai_proto_rawDesc
)

func file_transport_grpc_proto_umai_proto_rawDescGZIP() []byte {
	file_transport_grpc_proto_umai_proto_rawDescOnce.Do(func() {
		file_transport_grpc_proto_umai_proto_rawDescData = protoimpl.X.CompressGZIP(file_transport_grpc_proto_umai_proto_rawDescData)
	})
	return file_transport_grpc_proto_umai_proto_rawDescData
}

var file_transport_grpc_proto_umai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transport_grpc_proto_umai_proto_goTypes = []interface{}{
	(*IdentityReq)(nil), // 0: grpc.IdentityReq
	(*IdentityRes)(nil), // 1: grpc.IdentityRes
}
var file_transport_grpc_proto_umai_proto_depIdxs = []int32{
	0, // 0: grpc.MenuAuthService.GetIdentity:input_type -> grpc.IdentityReq
	1, // 1: grpc.MenuAuthService.GetIdentity:output_type -> grpc.IdentityRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_grpc_proto_umai_proto_init() }
func file_transport_grpc_proto_umai_proto_init() {
	if File_transport_grpc_proto_umai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transport_grpc_proto_umai_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transport_grpc_proto_umai_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transport_grpc_proto_umai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_grpc_proto_umai_proto_goTypes,
		DependencyIndexes: file_transport_grpc_proto_umai_proto_depIdxs,
		MessageInfos:      file_transport_grpc_proto_umai_proto_msgTypes,
	}.Build()
	File_transport_grpc_proto_umai_proto = out.File
	file_transport_grpc_proto_umai_proto_rawDesc = nil
	file_transport_grpc_proto_umai_proto_goTypes = nil
	file_transport_grpc_proto_umai_proto_depIdxs = nil
}
